import ssl
import re
import requests

requests.adapters.DEFAULT_RETRIES = 5
ssl._create_default_https_context = ssl._create_unverified_context
requests.packages.urllib3.disable_warnings()
requests_with_session = requests.Session()


def obtain_js(html):
    js = '<script src="(.*?)"'
    href = re.compile(js, re.S).findall(html)
    return href


js_code = {
    'XDFsK2hRQrEAMJtR': 'xmShQQ7SaY3',
    'hSNQnPyN3zf3jbQz': 'pNT8tdaT',
    'MGYaYRCEp5JARsBT': 'YS2AWje',
    'knBe7batAktyw2MB': 'i6R5FwWwbAyH',
    'XwrzkzZ5nr4w6FWi': 'A7hYcwdThpfXDs',
    'JBQdQwZ75idj747i': 'sECk8n',
    'kwBQ6zAazmP7fcpZ': 'GfrjAs',
    'fJ3FeX2MWmxGP4MW': 'CQ2w8Kx6QitBZh7',
    'APp6QpMm56RTQXFn': 'RAFBQsSQ8PD',
    'MSeFjttBD3nTCtwH': '2WMpkYnmZ5',
    'PY3cN4imk5EQThnF': 'XSCF37jDYdz',
    'PQpjAnxt68SZ7xTK': 'GhBikixQsJEr',
    'YaSp7MxDxwweMNHc': 'rJh5pd8Bi6tk2Jm',
    'ZphPm2MWPXaXe4wd': '6F8an8GmKh2pjAN',
    'QfKXDYT5MXJj6z8c': 'Y752kB',
    'rDdQD8f8rwF7jFjz': 'YdNtiF',
    '8rhZ5QcMMfMm5pCa': 'cr3bjxZAJ7AMF3y',
    'b5NMSASXRKFSsBG3': 'Zm67%C3%86YF',
    'pCMa3yDitNJ4MNxZ': 'Em6rya32Qs4p',
    'QA8KwfM2tZRaBCKp': '3mDxm5cz7Sbk',
    'FkbhKtzPmHEKZa4Q': 'NSSJyYp53',
    'w4BZ4n6jymP6CKcS': 'Sn6iBrnQn',
    'prHnnwfSfYsprrC8': 'dcsBzzizpiS6Y7f',
    't3DHEF5Hxsf3NjSi': 'QMss78iaxK',
    '7hWyFHt4pr2AF3BE': 'ZfZG2mSaKDC',
    'SzNebPNzGbkaETnW': 'KzZJcpGyJe',
    'HGFxTc7PYDJtB86c': 'BmQAzZzPxBsH7xX',
    'ZcBhmx8NiWEpxerk': 'mRKtQBCiCenPS',
    'eCAiwFMydcTrxeW5': 'nAx8ekydKYs',
    'HGZKrGt5ABT8QfNa': 'ezYw3f',
    'ibKXDX8dtcRTCpdZ': 'DeDM7aSKfmKDD8',
    'dHSYWKZyEfFZFWAy': 'DymFXaDw',
    'ZFQdjnFzRHp5n7wn': '6ArCwESBD4',
    'T7JiQnstDmEDihJE': 'tz3JpJ',
    '2k3Qa2FtdtZD3T63': '7GxakmDpmxz',
    'FRnWXMx8Qd6akF38': 'fzaapfSpixhw',
    'C26ze47mCCNXppxY': 'TKMGmdRcMmB7f',
    'c8aFXkGXtStRXWCe': 'nym5pzyS8sTzMp',
    '3PDbtG4y2EbCwXeS': 'p7amPiTBWMm',
    'Tzj36Qe5kD3iFH4N': 'rb5Eij4nKJi',
    'ZAh2sRExKjd6X3Kp': 'YKQh5M8fm8',
    'wCGybQXrDHPQeM5B': 'PQnjzYN7nEsD',
    '4bAEGCeQ5EjTWSsC': 'MR5CzSmKs8aK',
    'AS4wt4wpk6sY4kbJ': 'ZpksXrYTT',
    'i6aktSYrpMs2X48y': 'wkzAYtS',
    'rTEYNRMaT7CexYZW': 'MERkHtxFzsZP',
    'S76AAffwzXPGGYki': 'fj7aHyJN',
    'kjmCcGchHriBrzNM': '6xTahhmpymQdhH',
    'PAhkcFtcXPkxMAic': 'mbjsGm',
    'hhJKPkkPCZNmpY6C': '6F7RiAJb',
    '28jhHRbfHQBjsecd': 'xdrbtN8M%C2%A5eJpm',
    's7SYKZepdwyG8taC': 'p6XPNBBR',
    'jxQ27QfSfWmhkGkk': 'Q3CXtGhwn',
    't66Dky7WDsAsbJDx': 'BpW47kne',
    'beb7srX24CGcwr7e': 'FMDDs4sBymznP',
    '6rQcWXfEj2aZi2Z2': 'n5HHWTS',
    'AQyRYXe5axkbDkMz': 'nZNkM6irGdb',
    'aR4RJnZARiijjnDA': 'nFDGYkYDfnca',
    '7BPwQxMX7z862TFf': 'GDi82CGxz',
    'py5zZ38pGEYi7fEr': '8H7SBmmXNQN',
    'Wbi7yrjtC37MCJkF': 'mc6hz6MN57ZX',
    'HMmjr5Kj6Dn7Hjcz': 'MW53STa25jaSzf',
    '4zBa4iHiZjMRaFGB': 'Q2WBATsSN',
    '3bzbNSkJE7t6CcHS': '3hpWAm3TzpDMK7b',
    'ERZYECATnk3rpy57': 'Rd7mhiBe',
    '5KT7Whe76jHa3M3F': 'iQmkpd335',
    'PebyiyYahBRTxD74': '7NAp7c2Qc',
    'MBmMtxNjrff6DJey': 'FY6cCjZWZHid',
    'MAzFQsYHehKRzzep': '225Q5hp4',
    'KRyKsS2D6ktz75fb': 'JZwSYP',
    'neXpwwKdzSpNdfmR': 'QDc28PEmPeZhWcd',
    'yntthnW7zGFpdnXk': 'YbBWtysQw78mF4D',
    '3ccftFcXbSJw6F3t': 'aCAbA7XXEZ6',
    'nHen28SZTwcf8nZm': 'iB7p8WNJifGM',
    'bbJfKEDp4KMTsT8w': 'm7J6fJ7KtXRZ',
    'Y4xBeJD6zXGRTnyB': '5GfKr4dwk',
    'DsZQTEXTNbkjMWZr': '53BSbfcpDyyJFc',
    'hesYDysNwKAMz5e5': 'Mf6wBQh7yhe',
    '3PTsCdrfyYiWjkeC': 'BRPMH5',
    'YTPhNW3a5h5nfwAk': 'ZmhfjkBX2f',
    'YFaM4BTAeWeS6Pbh': 'wJWrphQp',
    'z7JbNX5hJipx3wJN': 'RQTM52XnkdcpAKA',
    '68hjEEbWxDiYn6by': 'sTKmM3nQBnQEx',
    'NJHB5zmPtt8zHHXw': 'MRSmY8r3mEJe4',
    'B7aZQHibD8wdAcG2': 'EW4dAH',
    '8zieCQ2xtBYx6pEJ': 'fxmWAsRMwM',
    'BDCDmSnKrfBGJZXE': 'DTb3RP6HttnwDS',
    '67nYG5rSWJtmmTK8': 'AAywFjhHrN8ZP',
    '28jhHRbfHQ': '',
    '7yAy5AbRT7RiRm43': 'HQsRKYa2Y',
    'ESsfTSZJwd4ZXkmA': '',
    '6hrt64i4SEsyFzfp': 'WYEGEY5hAD5',
    'ctf4Ki8BbKsB8NpT': 'Q75N7RCr',
    'ZRE25YEF5rzees8P': '',
    'tw3RDcGtQT3mNaiQ': '',
    '6HK8DYhSJXziWxtC': '',
    'pDbG6aHte2b3Q8iG': '7GxakmDpmxz',
    'rhJnmJbyTXefSKcx': 'KKfixBstziEJjYj',
    'dABf7twxc7Efmyfm': 'RAFBQsSQ8PD',
    'MNDYE4jdKm3zxhF4': '',
    'NAcyx8EyssQ4tazr': '5xNxN6252p7QGT',
    "dDTmZb5PWmQsPQFm":'Ni24hmztCa',
    'GB7SAeMK4KDEDKHz':'BrdHPYENA',
    'PXPYws7pZtw328nt':"E5YRWDQN",
    'atQZbWbRRPiZsNTZ':'bnEh8GX3',
    '':'',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '', '':'', '':'', '':'',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '', '':'', '':'', '':'', '':'', '':'', '':'', '':'',










}